apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c8izo217p-java-quarkus
  janus-idp.io/tekton: c8izo217p-java-quarkus
  backstage.io/kubernetes-id: c8izo217p-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c8izo217p-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
